# Simple workflow for deploying static content to GitHub Pages
name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Test
        run: |
          npx playwright install
          npm run test
